import axios from 'axios';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { BsSearch } from 'react-icons/bs';

export default function Home() {
  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  // useEffect(() => {
  //   axios
  //     .get(
  //       `
  //   https://api.openweathermap.org/data/2.5/weather?q=athens&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`
  //     )
  //     .then((res) => console.log(res.data));
  // }, []);

  const fetchWeather = (e: any) => {
    e.preventDefault();
    setLoading(true);
    axios
      .get(
        `
    https://api.openweathermap.org/data/2.5/weather?q=athens&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`
      )
      .then((res) => {
        setWeather(res.data);
        setLoading(false);
        setCity('');
        console.log(res.data);
      })
      .catch((err) => {
        console.log(err);
        setLoading(false);
      });
  };

  return (
    <>
      <Head>
        <title>Weather - Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={fetchWeather}>Fetch data</button>
    </>
  );
}
